// Generated by CoffeeScript 1.10.0
var misspell, revspellcheck;

revspellcheck = require("./reverse-spellcheck.json");

misspell = function(text, caps, capsTypes, misspellPercent) {
  var capsType, i, j, k, l, len, len1, len2, len3, letter, letterToSwap, letterToSwapIndex, letters, m, misspellType, newWords, randomCapLetter, startCaps, upperPartOfWord, w, word, words, wordx, x;
  words = text.split(" ");
  if (capsTypes != null) {
    capsType = capsTypes[misspell.random(0, capsTypes.length)];
  } else {
    capsType = misspell.random(1, 7);
  }
  newWords = [];
  startCaps = null;
  if (misspellPercent != null) {
    null;
  } else {

  }
  for (w = j = 0, len = words.length; j < len; w = ++j) {
    word = words[w];
    letters = word.split("");
    if (misspell.random(0, 101) <= misspellPercent) {
      misspellType = misspell.random(1, 3);
      switch (misspellType) {
        case 1:
          letterToSwapIndex = misspell.random(0, letters.length - 1);
          letterToSwap = letters[letterToSwapIndex];
          letters[letterToSwapIndex] = letters[letterToSwapIndex + 1];
          letters[letterToSwapIndex + 1] = letterToSwap;
          break;
        case 2:
          if (revspellcheck[word] != null) {
            words[w] = revspellcheck[word];
          } else {
            for (x = k = 0, len1 = words.length; k < len1; x = ++k) {
              wordx = words[x];
              if (revspellcheck[wordx] != null) {
                words[x] = revspellcheck[wordx];
                break;
              }
            }
          }
      }
    }
    if (caps === true) {
      if (startCaps !== true) {
        switch (capsType) {
          case 1:
            letters[0] = letters[0].toUpperCase();
            break;
          case 2:
            if (misspell.random(0, 2) === 0) {
              letters[0] = letters[0].toUpperCase();
            }
            break;
          case 3:
            letters = letters.join("").toUpperCase().split("");
            break;
          case 4:
            letters = letters.join("").toLowerCase().split("");
            break;
          case 5:
            for (i = l = 0, len2 = letters.length; l < len2; i = ++l) {
              letter = letters[i];
              randomCapLetter = misspell.random(0, 3);
              switch (randomCapLetter) {
                case 0:
                  letters[i] = letter.toUpperCase();
                  break;
                case 1:
                  letters[i] = letter.toLowerCase();
              }
            }
            break;
          case 6:
            for (i = m = 0, len3 = letters.length; m < len3; i = ++m) {
              letter = letters[i];
              if (misspell.random(0, text.length) === misspell.random(0, text.length) && startCaps !== true) {
                startCaps = true;
                upperPartOfWord = letters.slice(i, letters.length).join("").toUpperCase().split("");
                letters = letters.slice(0, i).concat(upperPartOfWord);
              }
            }
        }
      } else if (startCaps === true) {
        letters = letters.join("").toUpperCase().split("");
      }
    }
    newWords.push(letters.join(""));
  }
  return newWords.join(" ");
};

misspell.random = function(min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
};

module.exports = misspell;

if (process.argv[5] != null) {
  console.log(misspell(String(process.argv[2]), String(process.argv[3]) === "true", JSON.parse(process.argv[4]), Number(process.argv[5])));
} else if (process.argv[4] != null) {
  console.log(misspell(String(process.argv[2]), String(process.argv[3]) === "true", JSON.parse(process.argv[4])));
} else if (process.argv[3] != null) {
  console.log(misspell(String(process.argv[2]), String(process.argv[3]) === "true"));
} else if (process.argv[2] != null) {
  console.log(misspell(String(process.argv[2]), true));
} else if (process.argv[1] != null) {
  console.log("You just ran Misspell without any arguments. You can use Misspell like a CLI if you'd like, just put the arguments in the same order you would using it in JavaScript.");
}
